<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>WinToolBox.Core</RootNamespace>
    <AssemblyName>WinToolBox.Core</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

</Project>
